### PR TITLE
Email fix

### PR DESCRIPTION
**Pull request by jaymcaliley**

### CODE REVIEW

**Comment by ldanielswakman** [comment]
Thanks for the improvements; the contact form 7 seems like a good catch, just wondering what happens to the u-mt40 class that was applied?

Regarding the email settings; shall we wait for Kerim to provide the Yandex details? Or do you want it merged right now to be able to have a working version for now?

EDIT: Just saw the email, and will drop the account info in here. Also: did you include the define('WPCF7_AUTOP', false); for the contact form 7 forms?

**Comment by ldanielswakman** [comment]
@jaymcaliley we updated the email config setting to match the Yandex settings; could you check if this is all okay and the branch can be merged? If you give the green light we can merge and deploy.

**Comment by jaymcaliley** [comment]
@ldanielswakman I think we can add the u-mt40 class in the shortcode, e.g.:

``` php
<?php echo do_shortcode( '[contact-form-7 id="139" title="Contact Us" html_class="u-mt40"]' ); ?>
```

in line 23 of `templates/header.php`... Haven't tested that; got it from here: http://contactform7.com/faq/can-i-add-id-and-class-attributes-to-a-form-element/

The email settings look good to me. Just be sure the YAZANE_EMAIL and YAZANE_PASSWORD are defined in wp-config.php. You should be able to merge the branch.

And yeah, the `WPCF7_AUTOP` setting is for the Contact Form 7 forms, to prevent it from adding `<br>` after each label.

**Comment by ldanielswakman** [comment]
Yeah İ've added the email/pw definitions in the wp_config file already and deployed it. İ'll merge this so we can do a test live.

**Pull request merged**
